import {Platform, StyleSheet, TextStyle, ViewStyle} from 'react-native';
import {CATEGORIES} from '../types/category';

export default StyleSheet.create({
    screenContainer: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
    },
    dropDownContainer: {
        borderRadius: 12,
        paddingHorizontal: 12,
        backgroundColor: '#ffffff',
        borderColor: '#cccccc',
        elevation: 5,
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.2,
        shadowRadius: 2,
        width: '100%',
        marginBottom: 20,
    },
    renderListItemContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#fafafa',
        borderRadius: 6,
        marginVertical: 2,
    },
    dropDownListStyle: {
        borderColor: '#e0e0e0',
        borderRadius: 8,
        backgroundColor: '#ffffff',
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    timerDisplayWrapper: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    timerDisplayContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderRadius: 16,
        width: 240,
        height: 240,
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    timerText: {
        fontSize: 60,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginTop: 20,
        marginBottom: Platform.OS === 'ios' ? 20 : 40,
    },
    button: {
        paddingVertical: 14,
        paddingHorizontal: 30,
        borderRadius: 10,
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        minWidth: 130,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    renderListItemLabel: {
        fontSize: 16,
    },
    addNewTimerContainer: {
        backgroundColor: '#eafbee',
        borderRadius: 6,
        borderLeftWidth: 4,
        borderLeftColor: '#4caf50',
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginVertical: 2,
    },
    addNewTimerLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#4caf50',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '90%',
        maxHeight: '85%',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 15,
        elevation: 10,
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.25,
        shadowRadius: 8,
        flexDirection: 'column',
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '600',
        marginBottom: 15,
        textAlign: 'center',
        color: '#333333',
    },
    modalKAV: {
        flex: 1,
        width: '100%',
        flexDirection: 'column',
    },
    modalScrollView: {
        flexGrow: 1,
        flexBasis: 0,
    },
    modalScrollViewContent: {
        paddingBottom: 10,
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 15,
    },
    cancelButton: {
        flex: 1,
        marginRight: 8,
        backgroundColor: '#e0e0e0',
        padding: 14,
        borderRadius: 8,
        alignItems: 'center',
    },
    saveButton: {
        flex: 1,
        marginLeft: 8,
        backgroundColor: '#4361ee',
        padding: 14,
        borderRadius: 8,
        alignItems: 'center',
    },
    cancelText: {color: '#444444', fontWeight: '500'},
    saveText: {color: '#ffffff', fontWeight: '500'},
    textInput: {
        borderWidth: 1,
        borderColor: '#cccccc',
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 8,
        marginBottom: 18,
        backgroundColor: '#fdfdfd',
        fontSize: 16,
        width: '100%',
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 8,
        color: '#444444',
    },
    datePickerContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 8,
        marginVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 180,
    },
    catGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginVertical: 8,
    },
    catChip: {
        flexBasis: '48%',
        paddingVertical: 12,
        paddingHorizontal: 8,
        borderRadius: 10,
        borderWidth: 1.5,
        marginBottom: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    catChipText: {
        fontWeight: '600',
        fontSize: 15,
        textAlign: 'center',
    },
});

export const getCategoryStyles = (categoryId: number): {
    container: ViewStyle;
    label: TextStyle;
} => {
    const accent = CATEGORIES.find(c => c.id === categoryId)?.accentColor ?? '#888888';
    return {
        container: {
            borderLeftWidth: 5,
            borderLeftColor: accent,
        },
        label: {
            color: accent,
            fontWeight: '600',
        },
    };
};
