// TimerScreen.styles.js
import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    screenContainer: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        justifyContent: 'space-between',
    },
    dropDownContainer: {
        marginTop: 20,
        marginBottom: 20,
        width: '90%',
        borderColor: '#e0e0e0',
        borderRadius: 8,
        paddingHorizontal: 10,
    },
    dropDownListStyle: {
        borderColor: '#e0e0e0',
        borderRadius: 8,
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    timerDisplayContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 40,
        backgroundColor: 'white',
        borderRadius: 16,
        width: 220,
        height: 220,
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    timerText: {
        fontSize: 56,
        fontWeight: 'bold',
        color: '#2c3e50',
        letterSpacing: 1,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '90%',
        marginTop: 20,
        marginBottom: 40,
    },
    button: {
        backgroundColor: '#4361ee',
        paddingVertical: 14,
        paddingHorizontal: 35,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        minWidth: 120,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    renderListItemContainer: {
        paddingVertical: 10,
        paddingHorizontal: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#eeeeee',
    },
    renderListItemLabel: {
        fontSize: 16,
        color: '#333333',
    },
    renderListItemDuration: {
        fontSize: 14,
        color: '#666666',
    },
});
